services:
  postgres:
    image: postgres:15
    container_name: pg-main
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa  # This is a default DB for the postgres user
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: postgres -c 'listen_addresses=0.0.0.0' # Allow connections from other containers
    
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meili
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

  redis:
    image: redis:7-alpine
    container_name: redis-main
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  strapi:
    build:
      context: ../strapi-v4
      dockerfile: Dockerfile
    container_name: strapi
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_v4
      DATABASE_USERNAME: medusa
      DATABASE_PASSWORD: medusa
      DATABASE_SSL: "false"
      APP_KEYS: "l6fmcJrZhPNusZqGc7GxQn7ncOq1ykDK,fEk4eJVX5rvKCcCda9YwKhVfMkixpYqG,9zP6M/uMtwSJXGqRTpvfa0LtBykz/mSJ,DbiME2UX29VRIR4Zz91V3DVcJeBQtOsC"
      JWT_SECRET: "ac3RW8iLJZ4BszGi6Hu1PPq+CsBLmlAW"
      ADMIN_JWT_SECRET: "mfi1bTJjmr1mBqgCu509B4Bd4gjkU7Bk"
      API_TOKEN_SALT: "NKsT8y6QBKEzt7p5AWL8QSmZ697su6j1"
      STRAPI_S3_REGION: us-east-1
      STRAPI_S3_BUCKET: gm-strapi-uploads
      STRAPI_S3_ACCESS_KEY_ID: AKIAV2BPJQVEVTNJ2MMK
      STRAPI_S3_SECRET_ACCESS_KEY: 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
      STRAPI_S3_BASE_URL: https://gm-strapi-sdf.s3.us-east-1.sdfsd.com
    ports:
      - "1337:1337"
    volumes:
      - ../strapi-v4:/opt/app
      - strapi_node_modules:/opt/app/node_modules
      - strapi_uploads:/opt/app/public/uploads

  db_setup:
    image: postgres:15
    container_name: db-setup
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "psql -U medusa -h pg-main -c 'CREATE DATABASE strapi_v4;'"
    networks:
      - default

volumes:
  pg_data:
  meili_data:
  redis_data:
  strapi_uploads:
  strapi_node_modules:

networks:
  default:
    external: false